---
- name: Actualizaciones de seguridad para todos los hosts
  hosts: all
  become: yes
  tasks:
    - name: Instalar actualizaciones de seguridad en Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
        only_upgrade: yes
        default_release: "{{ ansible_distribution_release }}-security"
      when: ansible_os_family == "Debian"

    - name: Instalar actualizaciones de seguridad en CentOS/RHEL 7
      yum:
        name: '*'
        security: yes
        state: latest
      when: ansible_distribution_major_version == '7' and (ansible_os_family == "RedHat")

    - name: Instalar actualizaciones de seguridad en CentOS/RHEL 8 y RHEL 9
      dnf:
        name: '*'
        security: yes
        state: latest
      when: (ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9') and (ansible_os_family == "RedHat")
