---
- name: Reiniciar Fedora Security Onion
  hosts: fedora_hosts
  become: yes  # Necesario para obtener privilegios de root.

  tasks:
    - name: Reiniciar la máquina
      ansible.builtin.reboot:
        msg: "Reiniciando por mantenimiento"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
