---
- name: Actualizar solo paquetes de seguridad en sistemas Linux y enviar notificaci贸n por correo
  hosts: all
  become: yes

  vars:
    gmail_username: "ifxsoc@gmail.com"
    gmail_password: "yhxm knft umiy omcf"
    mail_recipient: "avargasl@ifxcorp.com"
    mail_subject: "Actualizaci贸n de Seguridad Completada"
    mail_body: "La actualizaci贸n de seguridad ha sido completada satisfactoriamente."

  tasks:
    - name: Actualizar solo paquetes de seguridad en sistemas basados en Debian (Ubuntu)
      when: ansible_os_family == 'Debian'
      apt:
        name: '*'
        state: latest
        update_cache: yes
        cache_valid_time: 3600
        allow_unauthenticated: yes
      register: debian_security_updates

    - name: Actualizar solo paquetes de seguridad en sistemas basados en Red Hat (CentOS, RHEL)
      when: ansible_os_family == 'RedHat'
      yum:
        name: '*'
        security: yes
        state: latest
      register: redhat_security_updates

    - name: Enviar notificaci贸n por correo usando mailx
      ansible.builtin.shell: |
        echo "{{ mail_body }}" | mailx -s "{{ mail_subject }}" -r "{{ gmail_username }}" -S smtp="smtp.gmail.com:587" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="{{ gmail_username }}" -S smtp-auth-password="{{ gmail_password }}" -S ssl-verify=ignore "{{ mail_recipient }}"
      delegate_to: localhost
      when: debian_security_updates.changed or redhat_security_updates.changed
