---
- name: Actualizar todos los sistemas
  hosts: all
  become: yes  # Necesario para obtener privilegios de root

  tasks:
    - name: Actualizar todos los paquetes en Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: Actualizar todos los paquetes en CentOS/RHEL 7 & 8
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] in ['7', '8']

    - name: Actualizar todos los paquetes en RHEL 9
      ansible.builtin.dnf:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == '9'
